-- Tagsテーブルの作成
CREATE TABLE IF NOT EXISTS tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Row Level Security (RLS) を有効化
ALTER TABLE tags ENABLE ROW LEVEL SECURITY;

-- 全ユーザーがタグを参照できるポリシー
CREATE POLICY "Enable read access for all users" ON tags
    FOR SELECT USING (true);

-- 全ユーザーがタグを挿入できるポリシー
CREATE POLICY "Enable insert for all users" ON tags
    FOR INSERT WITH CHECK (true);

-- 全ユーザーがタグを削除できるポリシー
CREATE POLICY "Enable delete for all users" ON tags
    FOR DELETE USING (true);

-- 基本タグを挿入
INSERT INTO tags (name) VALUES 
  ('簡単'),
  ('時短'),
  ('ヘルシー'),
  ('節約'),
  ('作り置き'),
  ('冷凍可能'),
  ('パーティー'),
  ('子供向け'),
  ('和風'),
  ('洋風'),
  ('中華'),
  ('スパイシー')
ON CONFLICT (name) DO NOTHING;

-- 作成結果を確認
SELECT * FROM tags ORDER BY name;
