begin;

alter table public.recipe_composite_sets
  add column if not exists share_permission text not null default 'viewer';

alter table public.recipe_composite_sets
  add column if not exists current_version_no integer not null default 1;

update public.recipe_composite_sets
set share_permission = coalesce(nullif(trim(share_permission), ''), 'viewer')
where share_permission is null
   or trim(share_permission) = '';

update public.recipe_composite_sets
set current_version_no = 1
where current_version_no is null
   or current_version_no < 1;

alter table public.recipe_composite_sets
  drop constraint if exists recipe_composite_sets_share_permission_check;

alter table public.recipe_composite_sets
  add constraint recipe_composite_sets_share_permission_check
  check (share_permission in ('viewer', 'copier', 'editor'));

create index if not exists idx_recipe_composite_sets_share_permission
  on public.recipe_composite_sets(share_permission);

create table if not exists public.recipe_composite_set_versions (
  id bigint generated by default as identity primary key,
  composite_set_id bigint not null references public.recipe_composite_sets(id) on delete cascade,
  version_no integer not null,
  snapshot jsonb not null,
  created_by uuid not null default auth.uid(),
  created_at timestamptz not null default now(),
  unique (composite_set_id, version_no)
);

create index if not exists idx_composite_set_versions_set_id_created_at
  on public.recipe_composite_set_versions(composite_set_id, created_at desc);

alter table public.recipe_composite_set_versions enable row level security;

drop policy if exists "composite_set_versions_select" on public.recipe_composite_set_versions;
create policy "composite_set_versions_select"
on public.recipe_composite_set_versions
for select
using (
  exists (
    select 1
    from public.recipe_composite_sets sets
    where sets.id = composite_set_id
      and (
        sets.created_by = auth.uid()
        or sets.is_public = true
      )
  )
);

drop policy if exists "composite_set_versions_insert" on public.recipe_composite_set_versions;
create policy "composite_set_versions_insert"
on public.recipe_composite_set_versions
for insert
with check (
  exists (
    select 1
    from public.recipe_composite_sets sets
    where sets.id = composite_set_id
      and (
        sets.created_by = auth.uid()
        or (sets.is_public = true and sets.share_permission = 'editor')
      )
  )
);

drop policy if exists "composite_set_versions_delete_own" on public.recipe_composite_set_versions;
create policy "composite_set_versions_delete_own"
on public.recipe_composite_set_versions
for delete
using (
  exists (
    select 1
    from public.recipe_composite_sets sets
    where sets.id = composite_set_id
      and sets.created_by = auth.uid()
  )
);

drop policy if exists "composite_sets_update_own" on public.recipe_composite_sets;
create policy "composite_sets_update_owner_or_editor"
on public.recipe_composite_sets
for update
using (
  created_by = auth.uid()
  or (is_public = true and share_permission = 'editor')
)
with check (
  created_by = auth.uid()
  or (is_public = true and share_permission = 'editor')
);

drop policy if exists "composite_set_items_insert_own" on public.recipe_composite_set_items;
create policy "composite_set_items_insert_owner_or_editor"
on public.recipe_composite_set_items
for insert
with check (
  exists (
    select 1
    from public.recipe_composite_sets sets
    where sets.id = composite_set_id
      and (
        sets.created_by = auth.uid()
        or (sets.is_public = true and sets.share_permission = 'editor')
      )
  )
);

drop policy if exists "composite_set_items_update_own" on public.recipe_composite_set_items;
create policy "composite_set_items_update_owner_or_editor"
on public.recipe_composite_set_items
for update
using (
  exists (
    select 1
    from public.recipe_composite_sets sets
    where sets.id = composite_set_id
      and (
        sets.created_by = auth.uid()
        or (sets.is_public = true and sets.share_permission = 'editor')
      )
  )
)
with check (
  exists (
    select 1
    from public.recipe_composite_sets sets
    where sets.id = composite_set_id
      and (
        sets.created_by = auth.uid()
        or (sets.is_public = true and sets.share_permission = 'editor')
      )
  )
);

drop policy if exists "composite_set_items_delete_own" on public.recipe_composite_set_items;
create policy "composite_set_items_delete_owner_or_editor"
on public.recipe_composite_set_items
for delete
using (
  exists (
    select 1
    from public.recipe_composite_sets sets
    where sets.id = composite_set_id
      and (
        sets.created_by = auth.uid()
        or (sets.is_public = true and sets.share_permission = 'editor')
      )
  )
);

insert into public.recipe_composite_set_versions (composite_set_id, version_no, snapshot, created_by, created_at)
select
  sets.id,
  1,
  jsonb_build_object(
    'dishName', sets.dish_name,
    'baseRecipeId', sets.base_recipe_id,
    'currentUsageAmount', sets.base_usage_amount,
    'salesPrice', sets.sales_price,
    'salesCount', sets.sales_count,
    'totalCompositeCost', sets.total_cost_tax_included,
    'isPublic', sets.is_public,
    'sharePermission', sets.share_permission,
    'rows', coalesce(items.rows, '[]'::jsonb)
  ),
  sets.created_by,
  coalesce(sets.updated_at, sets.created_at, now())
from public.recipe_composite_sets sets
left join (
  select
    composite_set_id,
    jsonb_agg(
      jsonb_build_object(
        'itemType', item_type,
        'recipeId', recipe_id,
        'usageAmount', usage_amount,
        'sortOrder', sort_order,
        'ingredient', ingredient_payload
      )
      order by sort_order asc, id asc
    ) as rows
  from public.recipe_composite_set_items
  group by composite_set_id
) items on items.composite_set_id = sets.id
on conflict (composite_set_id, version_no) do nothing;

commit;
