create table if not exists public.recipe_composite_sets (
    id bigint generated by default as identity primary key,
    created_by uuid not null default auth.uid(),
    dish_name text not null,
    base_recipe_id bigint not null references public.recipes(id) on delete restrict,
    base_usage_amount numeric(12, 3),
    sales_price numeric(12, 2),
    sales_count numeric(12, 2),
    total_cost_tax_included numeric(12, 2),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.recipe_composite_set_items (
    id bigint generated by default as identity primary key,
    composite_set_id bigint not null references public.recipe_composite_sets(id) on delete cascade,
    recipe_id bigint not null references public.recipes(id) on delete restrict,
    usage_amount numeric(12, 3),
    sort_order integer not null default 0,
    created_at timestamptz not null default now()
);

create index if not exists idx_recipe_composite_sets_created_by
    on public.recipe_composite_sets(created_by);
create index if not exists idx_recipe_composite_set_items_set_id
    on public.recipe_composite_set_items(composite_set_id);

alter table public.recipe_composite_sets enable row level security;
alter table public.recipe_composite_set_items enable row level security;

drop policy if exists "composite_sets_select_own" on public.recipe_composite_sets;
create policy "composite_sets_select_own"
on public.recipe_composite_sets
for select
using (created_by = auth.uid());

drop policy if exists "composite_sets_insert_own" on public.recipe_composite_sets;
create policy "composite_sets_insert_own"
on public.recipe_composite_sets
for insert
with check (created_by = auth.uid());

drop policy if exists "composite_sets_update_own" on public.recipe_composite_sets;
create policy "composite_sets_update_own"
on public.recipe_composite_sets
for update
using (created_by = auth.uid())
with check (created_by = auth.uid());

drop policy if exists "composite_sets_delete_own" on public.recipe_composite_sets;
create policy "composite_sets_delete_own"
on public.recipe_composite_sets
for delete
using (created_by = auth.uid());

drop policy if exists "composite_set_items_select_own" on public.recipe_composite_set_items;
create policy "composite_set_items_select_own"
on public.recipe_composite_set_items
for select
using (
    exists (
        select 1
        from public.recipe_composite_sets sets
        where sets.id = composite_set_id
          and sets.created_by = auth.uid()
    )
);

drop policy if exists "composite_set_items_insert_own" on public.recipe_composite_set_items;
create policy "composite_set_items_insert_own"
on public.recipe_composite_set_items
for insert
with check (
    exists (
        select 1
        from public.recipe_composite_sets sets
        where sets.id = composite_set_id
          and sets.created_by = auth.uid()
    )
);

drop policy if exists "composite_set_items_update_own" on public.recipe_composite_set_items;
create policy "composite_set_items_update_own"
on public.recipe_composite_set_items
for update
using (
    exists (
        select 1
        from public.recipe_composite_sets sets
        where sets.id = composite_set_id
          and sets.created_by = auth.uid()
    )
)
with check (
    exists (
        select 1
        from public.recipe_composite_sets sets
        where sets.id = composite_set_id
          and sets.created_by = auth.uid()
    )
);

drop policy if exists "composite_set_items_delete_own" on public.recipe_composite_set_items;
create policy "composite_set_items_delete_own"
on public.recipe_composite_set_items
for delete
using (
    exists (
        select 1
        from public.recipe_composite_sets sets
        where sets.id = composite_set_id
          and sets.created_by = auth.uid()
    )
);
