-- Per-user recipe favorites (starred recipes)
BEGIN;

CREATE TABLE IF NOT EXISTS public.recipe_favorites (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  viewer_user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  recipe_id bigint NOT NULL,
  favorited_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS recipe_favorites_user_recipe_unique
  ON public.recipe_favorites (viewer_user_id, recipe_id);

CREATE INDEX IF NOT EXISTS idx_recipe_favorites_user_favorited_at
  ON public.recipe_favorites (viewer_user_id, favorited_at DESC);

ALTER TABLE public.recipe_favorites ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS recipe_favorites_authenticated_access ON public.recipe_favorites;

CREATE POLICY recipe_favorites_authenticated_access
  ON public.recipe_favorites
  FOR ALL
  TO authenticated
  USING (viewer_user_id = (SELECT auth.uid()))
  WITH CHECK (viewer_user_id = (SELECT auth.uid()));

COMMIT;
