create table if not exists recent_views (
  id bigint generated by default as identity primary key,
  recipe_id uuid references recipes(id) on delete cascade not null,
  viewed_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(recipe_id)
);

-- Enable RLS
alter table recent_views enable row level security;

create policy "Enable access to all users" on recent_views for all using (true) with check (true);
