create table deleted_recipes (
  id bigint generated by default as identity primary key,
  original_id bigint, -- ID from the main recipes table
  title text not null,
  description text,
  image text,
  prep_time text,
  cook_time text,
  servings text,
  tags text[],
  ingredients jsonb,
  steps text[],
  created_at timestamp with time zone, -- Original creation time
  deleted_at timestamp with time zone default timezone('utc'::text, now()) not null
);
